import Link from 'next/link';
import { ArrowLeft, Mail, MapPin, Phone, Printer } from 'lucide-react';
import { notFound } from 'next/navigation';
import { getCurrentProfile, getEmployeeDetail } from '@/lib/data';
import { PageHeader } from '@/components/page-header';
import { StatusPill } from '@/components/status-pill';
import { AssignAssetButton } from '@/components/assign-asset-button';

type Relation = { name: string } | null;

export default async function EmployeeDetailPage({ params }: { params: { id: string } }) {
  const [employee, profile] = await Promise.all([getEmployeeDetail(params.id), getCurrentProfile()]);
  if (!employee) notFound();
  const canEdit = profile?.role !== 'viewer';
  const location = employee.location as Relation;
  return <div className="mx-auto max-w-[1200px] px-6 pb-12 pt-16 sm:px-10 lg:px-14 lg:pt-20">
    <Link href="/employees" className="mb-5 inline-flex items-center gap-2 text-xs font-semibold text-moss hover:underline"><ArrowLeft size={14} />Back to employees</Link>
    <PageHeader eyebrow="Employee snapshot" title={employee.full_name} description={employee.job_title ?? 'Team member'} action={<div className="flex flex-wrap gap-2"><Link href={`/employees/${employee.id}/handover`} className="flex items-center gap-2 rounded-lg border border-[#cbd6cb] bg-white px-3 py-2.5 text-xs font-semibold text-ink/70 hover:border-moss hover:text-moss"><Printer size={14} />Handover document</Link>{canEdit && <AssignAssetButton employeeId={employee.id} employeeName={employee.full_name} />}</div>} />
    <div className="grid gap-5 lg:grid-cols-[0.72fr_1.28fr]">
      <section className="border border-[#dfe5df] bg-white p-5 sm:p-6"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-sage font-display text-lg font-semibold text-moss">{employee.full_name.split(' ').map((part: string) => part[0]).join('').slice(0, 2).toUpperCase()}</div><div><h2 className="font-display text-xl font-semibold">{employee.full_name}</h2><p className="mt-1 text-sm text-ink/50">{employee.active ? 'Active employee' : 'Inactive employee'}</p></div></div><dl className="mt-7 space-y-4 border-t border-[#edf0ed] pt-5 text-sm"><div className="flex gap-3"><Mail size={15} className="mt-0.5 text-moss" /><div><dt className="text-[10px] uppercase tracking-[0.1em] text-ink/35">Email</dt><dd className="mt-1 text-ink/70">{employee.email}</dd></div></div><div className="flex gap-3"><Phone size={15} className="mt-0.5 text-moss" /><div><dt className="text-[10px] uppercase tracking-[0.1em] text-ink/35">Phone</dt><dd className="mt-1 text-ink/70">{employee.phone ?? 'Not provided'}</dd></div></div><div className="flex gap-3"><MapPin size={15} className="mt-0.5 text-moss" /><div><dt className="text-[10px] uppercase tracking-[0.1em] text-ink/35">Location</dt><dd className="mt-1 text-ink/70">{location?.name ?? 'Not provided'}</dd></div></div><div><dt className="text-[10px] uppercase tracking-[0.1em] text-ink/35">Department</dt><dd className="mt-1 text-ink/70">{employee.department}</dd></div><div><dt className="text-[10px] uppercase tracking-[0.1em] text-ink/35">Job title</dt><dd className="mt-1 text-ink/70">{employee.job_title ?? 'Not provided'}</dd></div><div><dt className="text-[10px] uppercase tracking-[0.1em] text-ink/35">Assets assigned</dt><dd className="mt-1 font-medium text-ink">{employee.assets.length}</dd></div></dl></section>
      <section className="border border-[#dfe5df] bg-white p-5 sm:p-6"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-moss">Equipment</p><h2 className="mt-1 font-display text-xl font-semibold">Assigned assets</h2></div><span className="text-xs text-ink/45">{employee.assets.length} total</span></div>{employee.assets.length ? <div className="space-y-3">{employee.assets.map((asset) => { const category = (Array.isArray(asset.categories) ? asset.categories[0] : asset.categories) as Relation; const assetLocation = (Array.isArray(asset.locations) ? asset.locations[0] : asset.locations) as Relation; return <Link key={asset.id} href={`/assets/${asset.id}`} className="block border border-[#edf0ed] p-4 transition-colors hover:border-moss"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-ink">{asset.name}</p><p className="mt-1 text-xs text-ink/45">{category?.name ?? 'Uncategorized'} · {asset.manufacturer || 'No brand'} {asset.model || ''}</p></div><StatusPill status={asset.status} /></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs text-ink/55 sm:grid-cols-4"><span>Serial: {asset.serial_number || '—'}</span><span>Tag: {asset.asset_tag}</span><span>Assigned: {asset.assigned_at ? new Date(asset.assigned_at).toLocaleDateString() : '—'}</span><span>Location: {assetLocation?.name ?? '—'}</span></div></Link>; })}</div> : <div className="border border-dashed border-[#cbd6cb] p-10 text-center text-sm text-ink/45">No assets are assigned to this employee.</div>}</section>
    </div>
  </div>;
}
