import { MapPin, Warehouse } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import { getCurrentProfile, getLocationSummaries } from '@/lib/data';
import { AddLocationButton } from '@/components/add-location-button';
import { DeleteButton } from '@/components/delete-button';

export default async function StoragePage() {
  const [locations, profile] = await Promise.all([getLocationSummaries(), getCurrentProfile()]);
  const canEdit = profile?.role !== 'viewer';
  const totalAssets = locations.reduce((total, location) => total + location.count, 0);
  const averageCapacity = locations.length ? Math.round(locations.reduce((total, location) => total + location.capacity, 0) / locations.length) : 0;
  return <div className="mx-auto max-w-[1400px] px-6 pb-12 pt-16 sm:px-10 lg:px-14 lg:pt-20"><PageHeader eyebrow="Locations" title="Storage" description="Know where every asset lives." action={canEdit ? <AddLocationButton /> : undefined} /><div className="mb-8 grid gap-4 md:grid-cols-3"><div className="border border-[#dfe5df] bg-white p-5"><p className="text-xs text-ink/50">Total locations</p><p className="mt-4 font-display text-3xl font-semibold">{locations.length}</p></div><div className="border border-[#dfe5df] bg-white p-5"><p className="text-xs text-ink/50">Assets in storage</p><p className="mt-4 font-display text-3xl font-semibold">{totalAssets}</p></div><div className="border border-[#dfe5df] bg-white p-5"><p className="text-xs text-ink/50">Average capacity</p><p className="mt-4 font-display text-3xl font-semibold">{averageCapacity}%</p></div></div>{locations.length === 0 ? <div className="border border-dashed border-[#cbd6cb] bg-white p-12 text-center text-sm text-ink/50">No storage locations found in Supabase.</div> : <div className="grid gap-4 md:grid-cols-2">{locations.map((location) => <article key={location.id} className="border border-[#dfe5df] bg-white p-6"><div className="flex items-start justify-between"><div className="flex gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-sage text-moss"><Warehouse size={19} /></div><div><h2 className="font-display text-lg font-semibold tracking-[-0.03em]">{location.name}</h2><p className="mt-1 flex items-center gap-1 text-xs text-ink/45"><MapPin size={12} />{location.address}</p></div></div>{canEdit && <div className="flex items-center gap-3"><span className="font-display text-lg font-semibold">{location.count}</span><DeleteButton table="locations" id={location.id} label={location.name} /></div>}</div><div className="mt-7"><div className="mb-2 flex justify-between text-[11px] text-ink/50"><span>Capacity used</span><span>{location.capacity}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#edf0ed]"><div className="h-full bg-moss" style={{ width: `${location.capacity}%` }} /></div></div></article>)}</div>}</div>;
}
