import { Search } from 'lucide-react';
import { getAssets } from '@/lib/data';
import { PageHeader } from '@/components/page-header';
import { StatusPill } from '@/components/status-pill';
import { AddAssetButton } from '@/components/add-asset-button';
import { EditAssetButton } from '@/components/edit-asset-button';
import { DeleteButton } from '@/components/delete-button';
import { ExportAssetsButton } from '@/components/export-assets-button';

export default async function AssetsPage() {
  const assets = await getAssets();
  return <div className="mx-auto max-w-[1400px] px-6 pb-12 pt-9 sm:px-10 lg:px-14 lg:pt-12"><PageHeader eyebrow="Inventory" title="Assets" description="Everything your team owns, in one clear view." action={<div className="flex flex-wrap gap-3"><ExportAssetsButton /><AddAssetButton /></div>} /><div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-ink/35" /><input placeholder="Search by name, tag, or serial number" className="h-10 w-full border border-[#dfe5df] bg-white pl-10 pr-4 text-sm outline-none placeholder:text-ink/35 focus:border-moss" /></div></div><div className="overflow-x-auto border border-[#dfe5df] bg-white"><table className="w-full min-w-[820px] text-left"><thead className="border-b border-[#e6ebe6] bg-[#fbfcf9] text-[10px] font-semibold uppercase tracking-[0.12em] text-ink/40"><tr><th className="px-5 py-3.5">Asset</th><th className="px-5 py-3.5">Category</th><th className="px-5 py-3.5">Status</th><th className="px-5 py-3.5">Assigned to</th><th className="px-5 py-3.5">Location</th><th className="px-5 py-3.5">Warranty</th><th className="px-5 py-3.5" aria-label="Actions" /></tr></thead><tbody className="divide-y divide-[#edf0ed]">{assets.map((asset) => <tr key={asset.id} className="text-[13px] hover:bg-[#fbfcf9]"><td className="px-5 py-4"><p className="font-semibold text-ink">{asset.name}</p><p className="mt-1 text-[11px] text-ink/40">{asset.assetTag} · {asset.serialNumber}</p></td><td className="px-5 py-4"><span className="rounded px-2 py-1 text-[11px] text-ink/65" style={{ backgroundColor: asset.categoryColor }}>{asset.category}</span></td><td className="px-5 py-4"><StatusPill status={asset.status} /></td><td className="px-5 py-4 text-ink/65">{asset.assignee || <span className="text-ink/35">Unassigned</span>}</td><td className="px-5 py-4 text-ink/65">{asset.location}</td><td className="px-5 py-4 text-ink/60">{asset.warrantyUntil}</td><td className="px-5 py-4"><div className="flex items-center gap-3"><EditAssetButton asset={asset} /><DeleteButton table="assets" id={asset.id} label={asset.name} /></div></td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-ink/40">Showing {assets.length} assets</p></div>;
}
